apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: mysql
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS app_db CHARACTER SET utf8mb4;
    GRANT ALL PRIVILEGES ON app_db.* TO 'app_user'@'%';
