apiVersion: batch/v1
kind: Job
metadata:
  name: todoapp-migrate
  namespace: todoapp
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 300
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: todoapp:local
          imagePullPolicy: IfNotPresent
          args: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - secretRef:
                name: app-secret
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
